# Generated by Django 5.1 on 2024-08-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('modalidad', models.CharField(max_length=100)),
                ('objetivo', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('clasificacion', models.FileField(blank=True, null=True, upload_to='clasificaciones/')),
            ],
        ),
        migrations.CreateModel(
            name='DatosDeportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('corredor', models.BooleanField(default=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ftp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulso', models.IntegerField()),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.deportista')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(max_length=100)),
                ('objetivo', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('valoracion_corredor', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('valoracion_director', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.deportista')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.evento')),
            ],
        ),
    ]
