# Generated by Django 5.1 on 2024-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
