# Generated by Django 5.1 on 2024-08-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_evento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
