# Generated by Django 5.1 on 2024-08-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_categoria_alter_evento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
    ]
