# Generated by Django 5.1 on 2024-08-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_evento_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
