# Generated by Django 5.1 on 2024-08-19 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_categoria_modalidad_alter_evento_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='color',
        ),
        migrations.AlterField(
            model_name='evento',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.modalidad'),
        ),
    ]
