# Generated by Django 5.1 on 2024-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_evento_color_alter_evento_modalidad'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.UniqueConstraint(fields=('evento', 'deportista'), name='unique_resultado_per_evento_deportista'),
        ),
    ]
