overrides:
  postcss: ^8.5.23
  deepmerge-ts: ^8.0.0
  brace-expansion: ^1.1.18
  js-yaml: ^4.3.2
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  prisma: true
  sharp: true
  unrs-resolver: true
